// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func AdminLogin(vm AdminLoginVM) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"pt-BR\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><meta name=\"description\" content=\"Acesso ao Painel Administrativo VorcaroZAP.\"><title>Entrar — Painel Administrativo — VorcaroZAP</title><link rel=\"stylesheet\" href=\"/static/css/app.css\"></head><body style=\"background-color: var(--color-bg); display: flex; align-items: center; justify-content: center; min-height: 100vh; margin: 0; padding: 1rem;\"><main style=\"width: 100%; max-width: 420px;\"><div class=\"card\" style=\"padding: 2rem; box-shadow: 0 4px 12px rgba(0,0,0,0.1);\"><header style=\"text-align: center; margin-bottom: 1.5rem;\"><div style=\"display: flex; align-items: center; justify-content: center; gap: 0.5rem; margin-bottom: 0.5rem;\"><h1 class=\"site-title\" style=\"margin: 0; font-size: 1.5rem;\">VorcaroZAP</h1><span class=\"badge\" style=\"background-color: #ffd580; color: #664d03;\">Admin</span></div><p style=\"margin: 0; color: var(--color-text-muted); font-size: 0.9rem;\">Autenticação individual com credenciais e segundo fator (MFA)</p></header>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if vm.FlashError != "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"editorial-notice\" style=\"border-left-color: #dc3545; background-color: #fff5f5; color: #721c24; margin-bottom: 1.25rem;\"><strong>Aviso de Autenticação</strong><p style=\"margin-top: 0.25rem;\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(vm.FlashError)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/pages/admin_login.templ`, Line: 29, Col: 54}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</p></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<form method=\"POST\" action=\"/admin/login\" novalidate>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if vm.ReturnTo != "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<input type=\"hidden\" name=\"return_to\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.ResolveAttributeValue(vm.ReturnTo)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/pages/admin_login.templ`, Line: 35, Col: 64}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "<div class=\"form-group\" style=\"margin-bottom: 1.25rem;\"><label for=\"username\" style=\"display: block; font-weight: 600; margin-bottom: 0.35rem;\">Usuário / Login</label> <input type=\"text\" id=\"username\" name=\"username\" class=\"filter-input\" style=\"width: 100%; box-sizing: border-box;\" required autofocus autocomplete=\"username\"></div><div class=\"form-group\" style=\"margin-bottom: 1.5rem;\"><label for=\"password\" style=\"display: block; font-weight: 600; margin-bottom: 0.35rem;\">Senha</label> <input type=\"password\" id=\"password\" name=\"password\" class=\"filter-input\" style=\"width: 100%; box-sizing: border-box;\" required autocomplete=\"current-password\"></div><button type=\"submit\" class=\"btn btn-primary\" style=\"width: 100%; justify-content: center; padding: 0.75rem;\">Continuar &rarr;</button></form><footer style=\"text-align: center; margin-top: 1.5rem; border-top: 1px solid var(--color-border); padding-top: 1rem;\"><a href=\"/\" class=\"nav-link\" style=\"font-size: 0.85rem; color: var(--color-text-muted);\">&larr; Voltar à página pública</a></footer></div></main></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
