// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/raphaieu/vorcarozap/web/components"
)

func AdminProfile(vm AdminProfileVM) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"pt-BR\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><meta name=\"description\" content=\"Meu Perfil e Segurança — VorcaroZAP.\"><title>Meu Perfil — Painel Administrativo — VorcaroZAP</title><link rel=\"stylesheet\" href=\"/static/css/app.css\"></head><body>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.AdminNav("perfil").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<main class=\"container\"><section class=\"card\" style=\"max-width: 680px; margin: 0 auto;\"><header style=\"margin-bottom: 1.5rem;\"><h1 class=\"page-title\" style=\"margin: 0;\">Meu Perfil e Segurança</h1><p class=\"page-subtitle\" style=\"margin: 0.25rem 0 0; color: var(--color-text-muted);\">Informações da sua conta e gerenciamento de credenciais</p></header>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if vm.FlashMessage != "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<div class=\"editorial-notice\" style=\"border-left-color: #198754; background-color: #f0fdf4; color: #0f5132; margin-bottom: 1.25rem;\"><strong>Sucesso</strong><p style=\"margin-top: 0.25rem;\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(vm.FlashMessage)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/pages/admin_profile.templ`, Line: 31, Col: 56}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</p></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		if vm.FlashError != "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<div class=\"editorial-notice\" style=\"border-left-color: #dc3545; background-color: #fff5f5; color: #721c24; margin-bottom: 1.25rem;\"><strong>Aviso</strong><p style=\"margin-top: 0.25rem;\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(vm.FlashError)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/pages/admin_profile.templ`, Line: 38, Col: 54}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</p></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "<div style=\"background-color: var(--color-card-bg); border: 1px solid var(--color-border); border-radius: 6px; padding: 1.25rem; margin-bottom: 1.75rem;\"><div style=\"display: flex; justify-content: space-between; align-items: center; flex-wrap: wrap; gap: 0.5rem;\"><div><div style=\"font-size: 1.15rem; font-weight: 600;\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(vm.User.DisplayName)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/pages/admin_profile.templ`, Line: 45, Col: 80}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</div><div style=\"color: var(--color-text-muted); font-size: 0.9rem;\">Login: <code>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(vm.User.Username)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/pages/admin_profile.templ`, Line: 47, Col: 40}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "</code></div></div><div style=\"display: flex; gap: 0.5rem; align-items: center;\"><span class=\"badge\" style=\"background-color: var(--color-badge-bg); color: var(--color-badge-text);\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var6 string
		templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(vm.User.RoleHuman)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/pages/admin_profile.templ`, Line: 52, Col: 28}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "</span> ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if vm.User.MFAEnabled {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "<span class=\"status-tag\" style=\"background-color: #d1e7dd; color: #0f5132;\">MFA Ativo</span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "<span class=\"status-tag\" style=\"background-color: #fff3cd; color: #664d03;\">MFA Pendente</span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "</div></div></div><!-- Formulário de Alteração de Senha --><div style=\"margin-bottom: 2rem;\"><h2 style=\"font-size: 1.15rem; margin-bottom: 0.5rem;\">Alterar Minha Senha</h2><p style=\"color: var(--color-text-muted); font-size: 0.85rem; margin-bottom: 1rem;\">Informe sua senha atual e a nova senha desejada (mínimo de 10 caracteres).</p><form method=\"POST\" action=\"/admin/perfil/senha\" novalidate><div class=\"form-group\" style=\"margin-bottom: 1rem;\"><label for=\"current_password\" style=\"display: block; font-weight: 600; margin-bottom: 0.35rem;\">Senha Atual</label> <input type=\"password\" id=\"current_password\" name=\"current_password\" class=\"filter-input\" style=\"width: 100%; box-sizing: border-box;\" required autocomplete=\"current-password\"></div><div class=\"form-group\" style=\"margin-bottom: 1.25rem;\"><label for=\"new_password\" style=\"display: block; font-weight: 600; margin-bottom: 0.35rem;\">Nova Senha</label> <input type=\"password\" id=\"new_password\" name=\"new_password\" class=\"filter-input\" style=\"width: 100%; box-sizing: border-box;\" required autocomplete=\"new-password\"></div><button type=\"submit\" class=\"btn btn-primary btn-sm\">Atualizar Senha</button></form></div><hr style=\"border: 0; border-top: 1px solid var(--color-border); margin: 1.5rem 0;\"><!-- Encerramento de Sessão --><div style=\"display: flex; justify-content: space-between; align-items: center; flex-wrap: wrap; gap: 1rem;\"><div><h3 style=\"font-size: 1rem; margin: 0 0 0.25rem;\">Encerrar Sessão</h3><p style=\"margin: 0; color: var(--color-text-muted); font-size: 0.85rem;\">Sair da área administrativa neste dispositivo.</p></div><form method=\"POST\" action=\"/admin/logout\"><button type=\"submit\" class=\"btn btn-outline btn-sm\" style=\"color: #dc3545; border-color: #dc3545;\">Sair do Sistema</button></form></div></section></main></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
