// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func AdminMFASetup(vm AdminMFASetupVM) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"pt-BR\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><meta name=\"description\" content=\"Configuração de Segundo Fator (MFA) — VorcaroZAP.\"><title>Configurar MFA — Painel Administrativo — VorcaroZAP</title><link rel=\"stylesheet\" href=\"/static/css/app.css\"></head><body style=\"background-color: var(--color-bg); display: flex; align-items: center; justify-content: center; min-height: 100vh; margin: 0; padding: 1rem;\"><main style=\"width: 100%; max-width: 480px;\"><div class=\"card\" style=\"padding: 2rem; box-shadow: 0 4px 12px rgba(0,0,0,0.1);\"><header style=\"text-align: center; margin-bottom: 1.5rem;\"><div style=\"display: flex; align-items: center; justify-content: center; gap: 0.5rem; margin-bottom: 0.5rem;\"><h1 class=\"site-title\" style=\"margin: 0; font-size: 1.5rem;\">VorcaroZAP</h1><span class=\"badge\" style=\"background-color: #ffd580; color: #664d03;\">Configuração MFA</span></div><p style=\"margin: 0; color: var(--color-text-muted); font-size: 0.9rem;\">Ative a autenticação em duas etapas (TOTP) para proteger sua conta e liberar acessos administrativos</p></header>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if vm.FlashError != "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"editorial-notice\" style=\"border-left-color: #dc3545; background-color: #fff5f5; color: #721c24; margin-bottom: 1.25rem;\"><strong>Aviso de Configuração</strong><p style=\"margin-top: 0.25rem;\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(vm.FlashError)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/pages/admin_mfa_setup.templ`, Line: 29, Col: 54}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</p></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<div class=\"editorial-notice\" style=\"margin-bottom: 1.25rem;\"><strong>Passo 1: Adicione ao seu Aplicativo Autenticador</strong><p style=\"margin-top: 0.35rem; font-size: 0.85rem;\">Abra seu app autenticador (Google Authenticator, Microsoft Authenticator, 1Password, Bitwarden, etc.) e adicione a conta manualmente usando a chave abaixo:</p><div style=\"background-color: #f8f9fa; border: 1px dashed var(--color-border); padding: 0.6rem; border-radius: 4px; text-align: center; margin-top: 0.5rem;\"><code style=\"font-size: 1.05rem; font-weight: bold; letter-spacing: 0.15rem; color: #0d6efd;\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(vm.Secret)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/pages/admin_mfa_setup.templ`, Line: 39, Col: 112}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</code></div><p style=\"margin-top: 0.4rem; font-size: 0.75rem; color: var(--color-text-muted); text-align: center;\">Ou clique no link direto se estiver no mesmo dispositivo: <a href=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 templ.SafeURL
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinURLErrs(templ.SafeURL(vm.URI))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/pages/admin_mfa_setup.templ`, Line: 42, Col: 96}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "\" style=\"color: var(--color-link);\">Abrir no Autenticador</a></p></div><form method=\"POST\" action=\"/admin/mfa/setup\" novalidate><div class=\"form-group\" style=\"margin-bottom: 1.5rem;\"><label for=\"code\" style=\"display: block; font-weight: 600; margin-bottom: 0.35rem; text-align: center;\">Passo 2: Confirme o código de 6 dígitos gerado</label> <input type=\"text\" id=\"code\" name=\"code\" class=\"filter-input\" style=\"width: 100%; box-sizing: border-box; text-align: center; font-size: 1.5rem; letter-spacing: 0.35rem; font-family: monospace;\" required autofocus maxlength=\"6\" inputmode=\"numeric\" pattern=\"[0-9]{6}\" autocomplete=\"one-time-code\"></div><button type=\"submit\" class=\"btn btn-primary\" style=\"width: 100%; justify-content: center; padding: 0.75rem;\">Confirmar e Ativar MFA &rarr;</button></form></div></main></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
