// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/raphaieu/vorcarozap/web/components"

func Admin() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"pt-BR\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><meta name=\"description\" content=\"Área administrativa protegida do VorcaroZAP.\"><title>Painel Administrativo — VorcaroZAP</title><link rel=\"stylesheet\" href=\"/static/css/app.css\"></head><body>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Header().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<main class=\"container\"><section class=\"card\" aria-label=\"Painel Administrativo\"><header style=\"margin-bottom: 1.5rem;\"><div style=\"display: flex; align-items: center; gap: 0.75rem; margin-bottom: 0.5rem;\"><h1 class=\"page-title\" style=\"margin: 0;\">Painel Administrativo</h1><span class=\"badge\" style=\"background-color: var(--color-badge-bg); color: var(--color-badge-text);\">Autenticado</span></div><p class=\"page-subtitle\" style=\"margin: 0; color: var(--color-text-muted);\">Área de pós-moderação e gestão editorial protegida.</p></header><div class=\"editorial-notice\" style=\"margin-bottom: 1.5rem;\" aria-label=\"Aviso de Fase do Painel\"><strong>Fase de Implantação (VZ-014)</strong><p style=\"margin-top: 0.5rem;\">O acesso administrativo está ativo e protegido por autenticação HTTP. As ferramentas operacionais de listagem de fontes, inspeção de candidatos descobertos e ações de moderação editorial (desaprovação, restauração e aprovação de quarentena) serão disponibilizadas nas próximas etapas do projeto (VZ-015 e VZ-016).</p></div><p style=\"font-size: 0.9rem; color: var(--color-text-muted);\">Nenhuma ação de mutação ou dado não público está exposto nesta fase inicial de proteção.</p></section></main></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
