// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countAdminCandidates = `-- name: CountAdminCandidates :one
SELECT count(*)
FROM monitoring_candidates c
WHERE
    (?1 = '' OR c.editorial_status = ?1)
    AND (?2 = '' OR c.suggested_grade = ?2)
    AND (?3 = '' OR c.monitoring_run_id = ?3)
    AND (?4 = '' OR c.created_at >= ?4)
    AND (
        ?5 = '' OR
        like(?5, c.entity_name, '\') OR
        like(?5, c.normalized_entity_name, '\') OR
        like(?5, c.target_entity_name, '\') OR
        like(?5, c.case_name, '\') OR
        like(?5, c.proposition, '\') OR
        like(?5, c.source_url, '\') OR
        like(?5, c.canonical_url, '\') OR
        like(?5, c.source_title, '\') OR
        like(?5, c.publisher_or_author, '\')
    )
`

type CountAdminCandidatesParams struct {
	FilterStatus      interface{} `json:"filter_status"`
	FilterGrade       interface{} `json:"filter_grade"`
	FilterRunID       interface{} `json:"filter_run_id"`
	FilterPeriodSince interface{} `json:"filter_period_since"`
	SearchQuery       interface{} `json:"search_query"`
}

func (q *Queries) CountAdminCandidates(ctx context.Context, arg CountAdminCandidatesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdminCandidates,
		arg.FilterStatus,
		arg.FilterGrade,
		arg.FilterRunID,
		arg.FilterPeriodSince,
		arg.SearchQuery,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAdminEvidenceSources = `-- name: CountAdminEvidenceSources :one
SELECT count(*)
FROM evidence_sources es
JOIN evidence ev ON ev.id = es.evidence_id
JOIN claims c ON c.id = ev.claim_id
JOIN relationships rel ON rel.id = c.relationship_id
JOIN entities subj ON subj.id = rel.subject_entity_id
LEFT JOIN entities tgt ON tgt.id = rel.target_entity_id
LEFT JOIN cases cs ON cs.id = rel.case_id
JOIN sources s ON s.id = es.source_id
WHERE
    (?1 = '' OR c.status = ?1)
    AND (?2 = '' OR es.status = ?2)
    AND (?3 = '' OR c.origin = ?3)
    AND (?4 = '' OR c.grade = ?4)
    AND (?5 = '' OR es.role = ?5)
    AND (?6 = '' OR es.created_at >= ?6)
    AND (
        ?7 = '' OR
        like(?7, subj.name, '\') OR
        like(?7, COALESCE(tgt.name, ''), '\') OR
        like(?7, COALESCE(cs.name, ''), '\') OR
        like(?7, c.proposition, '\') OR
        like(?7, s.title, '\') OR
        like(?7, s.publisher_or_author, '\') OR
        like(?7, s.canonical_url, '\') OR
        like(?7, s.original_url, '\') OR
        like(?7, es.excerpt, '\')
    )
`

type CountAdminEvidenceSourcesParams struct {
	FilterClaimStatus          interface{} `json:"filter_claim_status"`
	FilterEvidenceSourceStatus interface{} `json:"filter_evidence_source_status"`
	FilterOrigin               interface{} `json:"filter_origin"`
	FilterGrade                interface{} `json:"filter_grade"`
	FilterRole                 interface{} `json:"filter_role"`
	FilterPeriodSince          interface{} `json:"filter_period_since"`
	SearchQuery                interface{} `json:"search_query"`
}

func (q *Queries) CountAdminEvidenceSources(ctx context.Context, arg CountAdminEvidenceSourcesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdminEvidenceSources,
		arg.FilterClaimStatus,
		arg.FilterEvidenceSourceStatus,
		arg.FilterOrigin,
		arg.FilterGrade,
		arg.FilterRole,
		arg.FilterPeriodSince,
		arg.SearchQuery,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAdminSources = `-- name: CountAdminSources :one
SELECT count(*)
FROM sources s
WHERE
    (?1 = '' OR s.source_access_status = ?1)
    AND (?2 = '' OR s.source_type = ?2)
    AND (?3 = '' OR s.created_at >= ?3)
    AND (
        ?4 = '' OR
        like(?4, s.title, '\') OR
        like(?4, s.publisher_or_author, '\') OR
        like(?4, s.canonical_url, '\') OR
        like(?4, s.original_url, '\')
    )
`

type CountAdminSourcesParams struct {
	FilterAccessStatus interface{} `json:"filter_access_status"`
	FilterSourceType   interface{} `json:"filter_source_type"`
	FilterPeriodSince  interface{} `json:"filter_period_since"`
	SearchQuery        interface{} `json:"search_query"`
}

func (q *Queries) CountAdminSources(ctx context.Context, arg CountAdminSourcesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdminSources,
		arg.FilterAccessStatus,
		arg.FilterSourceType,
		arg.FilterPeriodSince,
		arg.SearchQuery,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAdminCandidateByID = `-- name: GetAdminCandidateByID :one
SELECT
    c.id,
    c.monitoring_run_id,
    c.fingerprint,
    c.fingerprint_version,
    c.entity_name,
    c.normalized_entity_name,
    c.target_entity_name,
    c.normalized_target_entity_name,
    c.case_name,
    c.normalized_case_name,
    c.relationship_type,
    c.proposition,
    c.suggested_grade,
    c.source_url,
    c.canonical_url,
    c.source_title,
    c.publisher_or_author,
    COALESCE(c.published_at, '') AS published_at,
    c.excerpt,
    c.locator,
    c.context_limits,
    c.technical_confidence,
    c.editorial_status,
    c.is_duplicate,
    c.duplicate_reason,
    COALESCE(c.canonical_candidate_id, '') AS canonical_candidate_id,
    COALESCE(c.resolved_subject_entity_id, '') AS resolved_subject_entity_id,
    COALESCE(c.resolved_target_entity_id, '') AS resolved_target_entity_id,
    COALESCE(c.resolved_case_id, '') AS resolved_case_id,
    COALESCE(c.published_claim_id, '') AS published_claim_id,
    c.structural_gate_passed,
    c.structural_gate_reasons,
    c.semantic_gate_passed,
    c.semantic_gate_reasons,
    c.policy_action,
    c.policy_reasons,
    c.created_at,
    c.updated_at,
    r.query AS run_query,
    r.status AS run_status,
    r.discovery_provider AS run_discovery_provider,
    r.discovery_model AS run_discovery_model,
    r.verification_provider AS run_verification_provider,
    r.verification_model AS run_verification_model,
    r.created_at AS run_created_at,
    COALESCE(subj.name, '') AS resolved_subject_name,
    COALESCE(subj.slug, '') AS resolved_subject_slug,
    COALESCE(tgt.name, '') AS resolved_target_name,
    COALESCE(tgt.slug, '') AS resolved_target_slug,
    COALESCE(cs.name, '') AS resolved_case_name,
    COALESCE(cs.slug, '') AS resolved_case_slug,
    COALESCE(clm.status, '') AS published_claim_status,
    COALESCE(clm.grade, '') AS published_claim_grade,
    COALESCE(clm.disposition, '') AS published_claim_disposition
FROM monitoring_candidates c
JOIN monitoring_runs r ON r.id = c.monitoring_run_id
LEFT JOIN entities subj ON subj.id = c.resolved_subject_entity_id
LEFT JOIN entities tgt ON tgt.id = c.resolved_target_entity_id
LEFT JOIN cases cs ON cs.id = c.resolved_case_id
LEFT JOIN claims clm ON clm.id = c.published_claim_id
WHERE c.id = ?
LIMIT 1
`

type GetAdminCandidateByIDRow struct {
	ID                         string        `json:"id"`
	MonitoringRunID            string        `json:"monitoring_run_id"`
	Fingerprint                string        `json:"fingerprint"`
	FingerprintVersion         int64         `json:"fingerprint_version"`
	EntityName                 string        `json:"entity_name"`
	NormalizedEntityName       string        `json:"normalized_entity_name"`
	TargetEntityName           string        `json:"target_entity_name"`
	NormalizedTargetEntityName string        `json:"normalized_target_entity_name"`
	CaseName                   string        `json:"case_name"`
	NormalizedCaseName         string        `json:"normalized_case_name"`
	RelationshipType           string        `json:"relationship_type"`
	Proposition                string        `json:"proposition"`
	SuggestedGrade             string        `json:"suggested_grade"`
	SourceUrl                  string        `json:"source_url"`
	CanonicalUrl               string        `json:"canonical_url"`
	SourceTitle                string        `json:"source_title"`
	PublisherOrAuthor          string        `json:"publisher_or_author"`
	PublishedAt                string        `json:"published_at"`
	Excerpt                    string        `json:"excerpt"`
	Locator                    string        `json:"locator"`
	ContextLimits              string        `json:"context_limits"`
	TechnicalConfidence        float64       `json:"technical_confidence"`
	EditorialStatus            string        `json:"editorial_status"`
	IsDuplicate                int64         `json:"is_duplicate"`
	DuplicateReason            string        `json:"duplicate_reason"`
	CanonicalCandidateID       string        `json:"canonical_candidate_id"`
	ResolvedSubjectEntityID    string        `json:"resolved_subject_entity_id"`
	ResolvedTargetEntityID     string        `json:"resolved_target_entity_id"`
	ResolvedCaseID             string        `json:"resolved_case_id"`
	PublishedClaimID           string        `json:"published_claim_id"`
	StructuralGatePassed       sql.NullInt64 `json:"structural_gate_passed"`
	StructuralGateReasons      string        `json:"structural_gate_reasons"`
	SemanticGatePassed         sql.NullInt64 `json:"semantic_gate_passed"`
	SemanticGateReasons        string        `json:"semantic_gate_reasons"`
	PolicyAction               string        `json:"policy_action"`
	PolicyReasons              string        `json:"policy_reasons"`
	CreatedAt                  string        `json:"created_at"`
	UpdatedAt                  string        `json:"updated_at"`
	RunQuery                   string        `json:"run_query"`
	RunStatus                  string        `json:"run_status"`
	RunDiscoveryProvider       string        `json:"run_discovery_provider"`
	RunDiscoveryModel          string        `json:"run_discovery_model"`
	RunVerificationProvider    string        `json:"run_verification_provider"`
	RunVerificationModel       string        `json:"run_verification_model"`
	RunCreatedAt               string        `json:"run_created_at"`
	ResolvedSubjectName        string        `json:"resolved_subject_name"`
	ResolvedSubjectSlug        string        `json:"resolved_subject_slug"`
	ResolvedTargetName         string        `json:"resolved_target_name"`
	ResolvedTargetSlug         string        `json:"resolved_target_slug"`
	ResolvedCaseName           string        `json:"resolved_case_name"`
	ResolvedCaseSlug           string        `json:"resolved_case_slug"`
	PublishedClaimStatus       string        `json:"published_claim_status"`
	PublishedClaimGrade        string        `json:"published_claim_grade"`
	PublishedClaimDisposition  string        `json:"published_claim_disposition"`
}

func (q *Queries) GetAdminCandidateByID(ctx context.Context, id string) (GetAdminCandidateByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getAdminCandidateByID, id)
	var i GetAdminCandidateByIDRow
	err := row.Scan(
		&i.ID,
		&i.MonitoringRunID,
		&i.Fingerprint,
		&i.FingerprintVersion,
		&i.EntityName,
		&i.NormalizedEntityName,
		&i.TargetEntityName,
		&i.NormalizedTargetEntityName,
		&i.CaseName,
		&i.NormalizedCaseName,
		&i.RelationshipType,
		&i.Proposition,
		&i.SuggestedGrade,
		&i.SourceUrl,
		&i.CanonicalUrl,
		&i.SourceTitle,
		&i.PublisherOrAuthor,
		&i.PublishedAt,
		&i.Excerpt,
		&i.Locator,
		&i.ContextLimits,
		&i.TechnicalConfidence,
		&i.EditorialStatus,
		&i.IsDuplicate,
		&i.DuplicateReason,
		&i.CanonicalCandidateID,
		&i.ResolvedSubjectEntityID,
		&i.ResolvedTargetEntityID,
		&i.ResolvedCaseID,
		&i.PublishedClaimID,
		&i.StructuralGatePassed,
		&i.StructuralGateReasons,
		&i.SemanticGatePassed,
		&i.SemanticGateReasons,
		&i.PolicyAction,
		&i.PolicyReasons,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RunQuery,
		&i.RunStatus,
		&i.RunDiscoveryProvider,
		&i.RunDiscoveryModel,
		&i.RunVerificationProvider,
		&i.RunVerificationModel,
		&i.RunCreatedAt,
		&i.ResolvedSubjectName,
		&i.ResolvedSubjectSlug,
		&i.ResolvedTargetName,
		&i.ResolvedTargetSlug,
		&i.ResolvedCaseName,
		&i.ResolvedCaseSlug,
		&i.PublishedClaimStatus,
		&i.PublishedClaimGrade,
		&i.PublishedClaimDisposition,
	)
	return i, err
}

const getAdminOverviewCounts = `-- name: GetAdminOverviewCounts :one
SELECT
    (SELECT count(*) FROM sources) AS total_sources,
    (SELECT count(*) FROM sources WHERE source_access_status = 'reachable') AS sources_reachable,
    (SELECT count(*) FROM sources WHERE source_access_status = 'unreachable') AS sources_unreachable,
    (SELECT count(*) FROM sources WHERE source_access_status = 'not_checked') AS sources_not_checked,
    (SELECT count(*) FROM sources WHERE source_access_status = 'cited_by_provider') AS sources_cited_by_provider,

    (SELECT count(*) FROM claims) AS total_claims,
    (SELECT count(*) FROM claims WHERE status = 'published') AS claims_published,
    (SELECT count(*) FROM claims WHERE status = 'quarantined') AS claims_quarantined,
    (SELECT count(*) FROM claims WHERE status = 'rejected') AS claims_rejected,
    (SELECT count(*) FROM claims WHERE status = 'archived') AS claims_archived,

    (SELECT count(*) FROM evidence_sources) AS total_evidence_sources,
    (SELECT count(*) FROM evidence_sources WHERE status = 'active') AS evidence_sources_active,
    (SELECT count(*) FROM evidence_sources WHERE status = 'rejected') AS evidence_sources_rejected,

    (SELECT count(*) FROM monitoring_candidates) AS total_candidates,
    (SELECT count(*) FROM monitoring_candidates WHERE editorial_status = 'quarantined') AS candidates_quarantined,
    (SELECT count(*) FROM monitoring_candidates WHERE editorial_status = 'published') AS candidates_published,
    (SELECT count(*) FROM monitoring_candidates WHERE editorial_status = 'rejected') AS candidates_rejected,
    (SELECT count(*) FROM monitoring_candidates WHERE editorial_status = 'archived') AS candidates_archived,
    (SELECT count(*) FROM monitoring_candidates WHERE is_duplicate = 1) AS candidates_duplicates,

    (SELECT count(*) FROM monitoring_runs) AS total_runs,
    (SELECT count(*) FROM monitoring_runs WHERE status = 'completed') AS runs_completed,
    (SELECT count(*) FROM monitoring_runs WHERE status = 'partial') AS runs_partial,
    (SELECT count(*) FROM monitoring_runs WHERE status = 'running') AS runs_running,
    (SELECT count(*) FROM monitoring_runs WHERE status = 'failed') AS runs_failed,
    (SELECT count(*) FROM monitoring_runs WHERE status = 'pending') AS runs_pending,

    (SELECT count(*) FROM entities) AS total_entities
`

type GetAdminOverviewCountsRow struct {
	TotalSources            int64 `json:"total_sources"`
	SourcesReachable        int64 `json:"sources_reachable"`
	SourcesUnreachable      int64 `json:"sources_unreachable"`
	SourcesNotChecked       int64 `json:"sources_not_checked"`
	SourcesCitedByProvider  int64 `json:"sources_cited_by_provider"`
	TotalClaims             int64 `json:"total_claims"`
	ClaimsPublished         int64 `json:"claims_published"`
	ClaimsQuarantined       int64 `json:"claims_quarantined"`
	ClaimsRejected          int64 `json:"claims_rejected"`
	ClaimsArchived          int64 `json:"claims_archived"`
	TotalEvidenceSources    int64 `json:"total_evidence_sources"`
	EvidenceSourcesActive   int64 `json:"evidence_sources_active"`
	EvidenceSourcesRejected int64 `json:"evidence_sources_rejected"`
	TotalCandidates         int64 `json:"total_candidates"`
	CandidatesQuarantined   int64 `json:"candidates_quarantined"`
	CandidatesPublished     int64 `json:"candidates_published"`
	CandidatesRejected      int64 `json:"candidates_rejected"`
	CandidatesArchived      int64 `json:"candidates_archived"`
	CandidatesDuplicates    int64 `json:"candidates_duplicates"`
	TotalRuns               int64 `json:"total_runs"`
	RunsCompleted           int64 `json:"runs_completed"`
	RunsPartial             int64 `json:"runs_partial"`
	RunsRunning             int64 `json:"runs_running"`
	RunsFailed              int64 `json:"runs_failed"`
	RunsPending             int64 `json:"runs_pending"`
	TotalEntities           int64 `json:"total_entities"`
}

func (q *Queries) GetAdminOverviewCounts(ctx context.Context) (GetAdminOverviewCountsRow, error) {
	row := q.db.QueryRowContext(ctx, getAdminOverviewCounts)
	var i GetAdminOverviewCountsRow
	err := row.Scan(
		&i.TotalSources,
		&i.SourcesReachable,
		&i.SourcesUnreachable,
		&i.SourcesNotChecked,
		&i.SourcesCitedByProvider,
		&i.TotalClaims,
		&i.ClaimsPublished,
		&i.ClaimsQuarantined,
		&i.ClaimsRejected,
		&i.ClaimsArchived,
		&i.TotalEvidenceSources,
		&i.EvidenceSourcesActive,
		&i.EvidenceSourcesRejected,
		&i.TotalCandidates,
		&i.CandidatesQuarantined,
		&i.CandidatesPublished,
		&i.CandidatesRejected,
		&i.CandidatesArchived,
		&i.CandidatesDuplicates,
		&i.TotalRuns,
		&i.RunsCompleted,
		&i.RunsPartial,
		&i.RunsRunning,
		&i.RunsFailed,
		&i.RunsPending,
		&i.TotalEntities,
	)
	return i, err
}

const listAdminCandidates = `-- name: ListAdminCandidates :many
SELECT
    c.id,
    c.monitoring_run_id,
    c.fingerprint,
    c.entity_name,
    c.target_entity_name,
    c.case_name,
    c.relationship_type,
    c.proposition,
    c.suggested_grade,
    c.source_url,
    c.canonical_url,
    c.source_title,
    c.publisher_or_author,
    COALESCE(c.published_at, '') AS published_at,
    c.excerpt,
    c.locator,
    c.context_limits,
    c.technical_confidence,
    c.editorial_status,
    c.is_duplicate,
    c.duplicate_reason,
    COALESCE(c.canonical_candidate_id, '') AS canonical_candidate_id,
    COALESCE(c.resolved_subject_entity_id, '') AS resolved_subject_entity_id,
    COALESCE(c.resolved_target_entity_id, '') AS resolved_target_entity_id,
    COALESCE(c.resolved_case_id, '') AS resolved_case_id,
    COALESCE(c.published_claim_id, '') AS published_claim_id,
    c.structural_gate_passed,
    c.semantic_gate_passed,
    c.policy_action,
    c.created_at,
    c.updated_at,
    r.query AS run_query,
    r.discovery_model AS run_discovery_model
FROM monitoring_candidates c
JOIN monitoring_runs r ON r.id = c.monitoring_run_id
WHERE
    (?1 = '' OR c.editorial_status = ?1)
    AND (?2 = '' OR c.suggested_grade = ?2)
    AND (?3 = '' OR c.monitoring_run_id = ?3)
    AND (?4 = '' OR c.created_at >= ?4)
    AND (
        ?5 = '' OR
        like(?5, c.entity_name, '\') OR
        like(?5, c.normalized_entity_name, '\') OR
        like(?5, c.target_entity_name, '\') OR
        like(?5, c.case_name, '\') OR
        like(?5, c.proposition, '\') OR
        like(?5, c.source_url, '\') OR
        like(?5, c.canonical_url, '\') OR
        like(?5, c.source_title, '\') OR
        like(?5, c.publisher_or_author, '\')
    )
ORDER BY c.created_at DESC, c.id DESC
LIMIT ?7 OFFSET ?6
`

type ListAdminCandidatesParams struct {
	FilterStatus      interface{} `json:"filter_status"`
	FilterGrade       interface{} `json:"filter_grade"`
	FilterRunID       interface{} `json:"filter_run_id"`
	FilterPeriodSince interface{} `json:"filter_period_since"`
	SearchQuery       interface{} `json:"search_query"`
	PageOffset        int64       `json:"page_offset"`
	PageLimit         int64       `json:"page_limit"`
}

type ListAdminCandidatesRow struct {
	ID                      string        `json:"id"`
	MonitoringRunID         string        `json:"monitoring_run_id"`
	Fingerprint             string        `json:"fingerprint"`
	EntityName              string        `json:"entity_name"`
	TargetEntityName        string        `json:"target_entity_name"`
	CaseName                string        `json:"case_name"`
	RelationshipType        string        `json:"relationship_type"`
	Proposition             string        `json:"proposition"`
	SuggestedGrade          string        `json:"suggested_grade"`
	SourceUrl               string        `json:"source_url"`
	CanonicalUrl            string        `json:"canonical_url"`
	SourceTitle             string        `json:"source_title"`
	PublisherOrAuthor       string        `json:"publisher_or_author"`
	PublishedAt             string        `json:"published_at"`
	Excerpt                 string        `json:"excerpt"`
	Locator                 string        `json:"locator"`
	ContextLimits           string        `json:"context_limits"`
	TechnicalConfidence     float64       `json:"technical_confidence"`
	EditorialStatus         string        `json:"editorial_status"`
	IsDuplicate             int64         `json:"is_duplicate"`
	DuplicateReason         string        `json:"duplicate_reason"`
	CanonicalCandidateID    string        `json:"canonical_candidate_id"`
	ResolvedSubjectEntityID string        `json:"resolved_subject_entity_id"`
	ResolvedTargetEntityID  string        `json:"resolved_target_entity_id"`
	ResolvedCaseID          string        `json:"resolved_case_id"`
	PublishedClaimID        string        `json:"published_claim_id"`
	StructuralGatePassed    sql.NullInt64 `json:"structural_gate_passed"`
	SemanticGatePassed      sql.NullInt64 `json:"semantic_gate_passed"`
	PolicyAction            string        `json:"policy_action"`
	CreatedAt               string        `json:"created_at"`
	UpdatedAt               string        `json:"updated_at"`
	RunQuery                string        `json:"run_query"`
	RunDiscoveryModel       string        `json:"run_discovery_model"`
}

func (q *Queries) ListAdminCandidates(ctx context.Context, arg ListAdminCandidatesParams) ([]ListAdminCandidatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAdminCandidates,
		arg.FilterStatus,
		arg.FilterGrade,
		arg.FilterRunID,
		arg.FilterPeriodSince,
		arg.SearchQuery,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminCandidatesRow
	for rows.Next() {
		var i ListAdminCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.MonitoringRunID,
			&i.Fingerprint,
			&i.EntityName,
			&i.TargetEntityName,
			&i.CaseName,
			&i.RelationshipType,
			&i.Proposition,
			&i.SuggestedGrade,
			&i.SourceUrl,
			&i.CanonicalUrl,
			&i.SourceTitle,
			&i.PublisherOrAuthor,
			&i.PublishedAt,
			&i.Excerpt,
			&i.Locator,
			&i.ContextLimits,
			&i.TechnicalConfidence,
			&i.EditorialStatus,
			&i.IsDuplicate,
			&i.DuplicateReason,
			&i.CanonicalCandidateID,
			&i.ResolvedSubjectEntityID,
			&i.ResolvedTargetEntityID,
			&i.ResolvedCaseID,
			&i.PublishedClaimID,
			&i.StructuralGatePassed,
			&i.SemanticGatePassed,
			&i.PolicyAction,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RunQuery,
			&i.RunDiscoveryModel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminEvidenceSources = `-- name: ListAdminEvidenceSources :many
SELECT
    es.id AS evidence_source_id,
    es.evidence_id,
    es.source_id,
    es.excerpt,
    es.locator,
    es.role,
    es.status AS evidence_source_status,
    es.created_at AS evidence_source_created_at,
    es.updated_at AS evidence_source_updated_at,
    ev.summary AS evidence_summary,
    ev.evidence_type,
    c.id AS claim_id,
    c.proposition AS claim_proposition,
    c.attribution AS claim_attribution,
    c.origin AS claim_origin,
    c.grade AS claim_grade,
    c.disposition AS claim_disposition,
    c.metric_eligible AS claim_metric_eligible,
    c.status AS claim_status,
    c.context_status AS claim_context_status,
    c.created_at AS claim_created_at,
    c.updated_at AS claim_updated_at,
    rel.id AS relationship_id,
    rel.relationship_type,
    rel.summary AS relationship_summary,
    rel.context_limits AS relationship_context_limits,
    subj.id AS subject_entity_id,
    subj.name AS subject_entity_name,
    subj.slug AS subject_entity_slug,
    COALESCE(tgt.id, '') AS target_entity_id,
    COALESCE(tgt.name, '') AS target_entity_name,
    COALESCE(tgt.slug, '') AS target_entity_slug,
    COALESCE(cs.id, '') AS case_id,
    COALESCE(cs.name, '') AS case_name,
    COALESCE(cs.slug, '') AS case_slug,
    s.title AS source_title,
    s.publisher_or_author AS source_publisher_or_author,
    s.original_url AS source_original_url,
    s.canonical_url AS source_canonical_url,
    s.source_type,
    s.source_access_status,
    COALESCE(s.source_access_checked_at, '') AS source_access_checked_at,
    s.http_status AS source_http_status,
    COALESCE(s.normalized_error_code, '') AS source_normalized_error_code
FROM evidence_sources es
JOIN evidence ev ON ev.id = es.evidence_id
JOIN claims c ON c.id = ev.claim_id
JOIN relationships rel ON rel.id = c.relationship_id
JOIN entities subj ON subj.id = rel.subject_entity_id
LEFT JOIN entities tgt ON tgt.id = rel.target_entity_id
LEFT JOIN cases cs ON cs.id = rel.case_id
JOIN sources s ON s.id = es.source_id
WHERE
    (?1 = '' OR c.status = ?1)
    AND (?2 = '' OR es.status = ?2)
    AND (?3 = '' OR c.origin = ?3)
    AND (?4 = '' OR c.grade = ?4)
    AND (?5 = '' OR es.role = ?5)
    AND (?6 = '' OR es.created_at >= ?6)
    AND (
        ?7 = '' OR
        like(?7, subj.name, '\') OR
        like(?7, COALESCE(tgt.name, ''), '\') OR
        like(?7, COALESCE(cs.name, ''), '\') OR
        like(?7, c.proposition, '\') OR
        like(?7, s.title, '\') OR
        like(?7, s.publisher_or_author, '\') OR
        like(?7, s.canonical_url, '\') OR
        like(?7, s.original_url, '\') OR
        like(?7, es.excerpt, '\')
    )
ORDER BY es.created_at DESC, es.id DESC
LIMIT ?9 OFFSET ?8
`

type ListAdminEvidenceSourcesParams struct {
	FilterClaimStatus          interface{} `json:"filter_claim_status"`
	FilterEvidenceSourceStatus interface{} `json:"filter_evidence_source_status"`
	FilterOrigin               interface{} `json:"filter_origin"`
	FilterGrade                interface{} `json:"filter_grade"`
	FilterRole                 interface{} `json:"filter_role"`
	FilterPeriodSince          interface{} `json:"filter_period_since"`
	SearchQuery                interface{} `json:"search_query"`
	PageOffset                 int64       `json:"page_offset"`
	PageLimit                  int64       `json:"page_limit"`
}

type ListAdminEvidenceSourcesRow struct {
	EvidenceSourceID          string        `json:"evidence_source_id"`
	EvidenceID                string        `json:"evidence_id"`
	SourceID                  string        `json:"source_id"`
	Excerpt                   string        `json:"excerpt"`
	Locator                   string        `json:"locator"`
	Role                      string        `json:"role"`
	EvidenceSourceStatus      string        `json:"evidence_source_status"`
	EvidenceSourceCreatedAt   string        `json:"evidence_source_created_at"`
	EvidenceSourceUpdatedAt   string        `json:"evidence_source_updated_at"`
	EvidenceSummary           string        `json:"evidence_summary"`
	EvidenceType              string        `json:"evidence_type"`
	ClaimID                   string        `json:"claim_id"`
	ClaimProposition          string        `json:"claim_proposition"`
	ClaimAttribution          string        `json:"claim_attribution"`
	ClaimOrigin               string        `json:"claim_origin"`
	ClaimGrade                string        `json:"claim_grade"`
	ClaimDisposition          string        `json:"claim_disposition"`
	ClaimMetricEligible       int64         `json:"claim_metric_eligible"`
	ClaimStatus               string        `json:"claim_status"`
	ClaimContextStatus        string        `json:"claim_context_status"`
	ClaimCreatedAt            string        `json:"claim_created_at"`
	ClaimUpdatedAt            string        `json:"claim_updated_at"`
	RelationshipID            string        `json:"relationship_id"`
	RelationshipType          string        `json:"relationship_type"`
	RelationshipSummary       string        `json:"relationship_summary"`
	RelationshipContextLimits string        `json:"relationship_context_limits"`
	SubjectEntityID           string        `json:"subject_entity_id"`
	SubjectEntityName         string        `json:"subject_entity_name"`
	SubjectEntitySlug         string        `json:"subject_entity_slug"`
	TargetEntityID            string        `json:"target_entity_id"`
	TargetEntityName          string        `json:"target_entity_name"`
	TargetEntitySlug          string        `json:"target_entity_slug"`
	CaseID                    string        `json:"case_id"`
	CaseName                  string        `json:"case_name"`
	CaseSlug                  string        `json:"case_slug"`
	SourceTitle               string        `json:"source_title"`
	SourcePublisherOrAuthor   string        `json:"source_publisher_or_author"`
	SourceOriginalUrl         string        `json:"source_original_url"`
	SourceCanonicalUrl        string        `json:"source_canonical_url"`
	SourceType                string        `json:"source_type"`
	SourceAccessStatus        string        `json:"source_access_status"`
	SourceAccessCheckedAt     string        `json:"source_access_checked_at"`
	SourceHttpStatus          sql.NullInt64 `json:"source_http_status"`
	SourceNormalizedErrorCode string        `json:"source_normalized_error_code"`
}

func (q *Queries) ListAdminEvidenceSources(ctx context.Context, arg ListAdminEvidenceSourcesParams) ([]ListAdminEvidenceSourcesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAdminEvidenceSources,
		arg.FilterClaimStatus,
		arg.FilterEvidenceSourceStatus,
		arg.FilterOrigin,
		arg.FilterGrade,
		arg.FilterRole,
		arg.FilterPeriodSince,
		arg.SearchQuery,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminEvidenceSourcesRow
	for rows.Next() {
		var i ListAdminEvidenceSourcesRow
		if err := rows.Scan(
			&i.EvidenceSourceID,
			&i.EvidenceID,
			&i.SourceID,
			&i.Excerpt,
			&i.Locator,
			&i.Role,
			&i.EvidenceSourceStatus,
			&i.EvidenceSourceCreatedAt,
			&i.EvidenceSourceUpdatedAt,
			&i.EvidenceSummary,
			&i.EvidenceType,
			&i.ClaimID,
			&i.ClaimProposition,
			&i.ClaimAttribution,
			&i.ClaimOrigin,
			&i.ClaimGrade,
			&i.ClaimDisposition,
			&i.ClaimMetricEligible,
			&i.ClaimStatus,
			&i.ClaimContextStatus,
			&i.ClaimCreatedAt,
			&i.ClaimUpdatedAt,
			&i.RelationshipID,
			&i.RelationshipType,
			&i.RelationshipSummary,
			&i.RelationshipContextLimits,
			&i.SubjectEntityID,
			&i.SubjectEntityName,
			&i.SubjectEntitySlug,
			&i.TargetEntityID,
			&i.TargetEntityName,
			&i.TargetEntitySlug,
			&i.CaseID,
			&i.CaseName,
			&i.CaseSlug,
			&i.SourceTitle,
			&i.SourcePublisherOrAuthor,
			&i.SourceOriginalUrl,
			&i.SourceCanonicalUrl,
			&i.SourceType,
			&i.SourceAccessStatus,
			&i.SourceAccessCheckedAt,
			&i.SourceHttpStatus,
			&i.SourceNormalizedErrorCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminSemanticEvaluationsByCandidateID = `-- name: ListAdminSemanticEvaluationsByCandidateID :many
SELECT
    se.id,
    se.monitoring_candidate_id,
    se.provider,
    se.model,
    se.schema_version,
    se.identity_match,
    se.claim_supported,
    se.claim_overstates_source,
    se.attribution_explicit,
    se.grade_compatible,
    se.contains_illicit_inference,
    se.uncertainties,
    se.recommended_action,
    se.created_at
FROM semantic_evaluations se
WHERE se.monitoring_candidate_id = ?
ORDER BY se.created_at ASC, se.id ASC
`

type ListAdminSemanticEvaluationsByCandidateIDRow struct {
	ID                       string `json:"id"`
	MonitoringCandidateID    string `json:"monitoring_candidate_id"`
	Provider                 string `json:"provider"`
	Model                    string `json:"model"`
	SchemaVersion            string `json:"schema_version"`
	IdentityMatch            int64  `json:"identity_match"`
	ClaimSupported           int64  `json:"claim_supported"`
	ClaimOverstatesSource    int64  `json:"claim_overstates_source"`
	AttributionExplicit      int64  `json:"attribution_explicit"`
	GradeCompatible          int64  `json:"grade_compatible"`
	ContainsIllicitInference int64  `json:"contains_illicit_inference"`
	Uncertainties            string `json:"uncertainties"`
	RecommendedAction        string `json:"recommended_action"`
	CreatedAt                string `json:"created_at"`
}

func (q *Queries) ListAdminSemanticEvaluationsByCandidateID(ctx context.Context, monitoringCandidateID string) ([]ListAdminSemanticEvaluationsByCandidateIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listAdminSemanticEvaluationsByCandidateID, monitoringCandidateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminSemanticEvaluationsByCandidateIDRow
	for rows.Next() {
		var i ListAdminSemanticEvaluationsByCandidateIDRow
		if err := rows.Scan(
			&i.ID,
			&i.MonitoringCandidateID,
			&i.Provider,
			&i.Model,
			&i.SchemaVersion,
			&i.IdentityMatch,
			&i.ClaimSupported,
			&i.ClaimOverstatesSource,
			&i.AttributionExplicit,
			&i.GradeCompatible,
			&i.ContainsIllicitInference,
			&i.Uncertainties,
			&i.RecommendedAction,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminSources = `-- name: ListAdminSources :many
SELECT
    s.id,
    s.title,
    s.publisher_or_author,
    s.original_url,
    s.canonical_url,
    COALESCE(s.published_at, '') AS published_at,
    COALESCE(s.accessed_at, '') AS accessed_at,
    s.source_type,
    s.source_access_status,
    COALESCE(s.source_access_checked_at, '') AS source_access_checked_at,
    s.http_status,
    COALESCE(s.normalized_error_code, '') AS normalized_error_code,
    s.created_at,
    s.updated_at,
    (SELECT count(*) FROM evidence_sources es WHERE es.source_id = s.id) AS total_uses,
    (SELECT count(*) FROM evidence_sources es WHERE es.source_id = s.id AND es.status = 'active') AS active_uses
FROM sources s
WHERE
    (?1 = '' OR s.source_access_status = ?1)
    AND (?2 = '' OR s.source_type = ?2)
    AND (?3 = '' OR s.created_at >= ?3)
    AND (
        ?4 = '' OR
        like(?4, s.title, '\') OR
        like(?4, s.publisher_or_author, '\') OR
        like(?4, s.canonical_url, '\') OR
        like(?4, s.original_url, '\')
    )
ORDER BY s.created_at DESC, s.id DESC
LIMIT ?6 OFFSET ?5
`

type ListAdminSourcesParams struct {
	FilterAccessStatus interface{} `json:"filter_access_status"`
	FilterSourceType   interface{} `json:"filter_source_type"`
	FilterPeriodSince  interface{} `json:"filter_period_since"`
	SearchQuery        interface{} `json:"search_query"`
	PageOffset         int64       `json:"page_offset"`
	PageLimit          int64       `json:"page_limit"`
}

type ListAdminSourcesRow struct {
	ID                    string        `json:"id"`
	Title                 string        `json:"title"`
	PublisherOrAuthor     string        `json:"publisher_or_author"`
	OriginalUrl           string        `json:"original_url"`
	CanonicalUrl          string        `json:"canonical_url"`
	PublishedAt           string        `json:"published_at"`
	AccessedAt            string        `json:"accessed_at"`
	SourceType            string        `json:"source_type"`
	SourceAccessStatus    string        `json:"source_access_status"`
	SourceAccessCheckedAt string        `json:"source_access_checked_at"`
	HttpStatus            sql.NullInt64 `json:"http_status"`
	NormalizedErrorCode   string        `json:"normalized_error_code"`
	CreatedAt             string        `json:"created_at"`
	UpdatedAt             string        `json:"updated_at"`
	TotalUses             int64         `json:"total_uses"`
	ActiveUses            int64         `json:"active_uses"`
}

func (q *Queries) ListAdminSources(ctx context.Context, arg ListAdminSourcesParams) ([]ListAdminSourcesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAdminSources,
		arg.FilterAccessStatus,
		arg.FilterSourceType,
		arg.FilterPeriodSince,
		arg.SearchQuery,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminSourcesRow
	for rows.Next() {
		var i ListAdminSourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.PublisherOrAuthor,
			&i.OriginalUrl,
			&i.CanonicalUrl,
			&i.PublishedAt,
			&i.AccessedAt,
			&i.SourceType,
			&i.SourceAccessStatus,
			&i.SourceAccessCheckedAt,
			&i.HttpStatus,
			&i.NormalizedErrorCode,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalUses,
			&i.ActiveUses,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
