// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: defense_statements.sql

package sqlc

import (
	"context"
)

const countAdminDefenseStatements = `-- name: CountAdminDefenseStatements :one
SELECT COUNT(*)
FROM defense_statements ds
`

func (q *Queries) CountAdminDefenseStatements(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdminDefenseStatements)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getDefenseStatementByID = `-- name: GetDefenseStatementByID :one
SELECT
    ds.id,
    ds.claim_id,
    ds.statement_type,
    ds.title,
    ds.content,
    ds.source_url,
    ds.contact_info,
    ds.status,
    ds.created_at,
    ds.updated_at,
    c.proposition AS claim_proposition,
    c.grade AS claim_grade,
    c.status AS claim_status,
    e.name AS entity_name,
    e.slug AS entity_slug
FROM defense_statements ds
JOIN claims c ON c.id = ds.claim_id
JOIN relationships r ON r.id = c.relationship_id
JOIN entities e ON e.id = r.subject_entity_id
WHERE ds.id = ?
`

type GetDefenseStatementByIDRow struct {
	ID               string `json:"id"`
	ClaimID          string `json:"claim_id"`
	StatementType    string `json:"statement_type"`
	Title            string `json:"title"`
	Content          string `json:"content"`
	SourceUrl        string `json:"source_url"`
	ContactInfo      string `json:"contact_info"`
	Status           string `json:"status"`
	CreatedAt        string `json:"created_at"`
	UpdatedAt        string `json:"updated_at"`
	ClaimProposition string `json:"claim_proposition"`
	ClaimGrade       string `json:"claim_grade"`
	ClaimStatus      string `json:"claim_status"`
	EntityName       string `json:"entity_name"`
	EntitySlug       string `json:"entity_slug"`
}

func (q *Queries) GetDefenseStatementByID(ctx context.Context, id string) (GetDefenseStatementByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getDefenseStatementByID, id)
	var i GetDefenseStatementByIDRow
	err := row.Scan(
		&i.ID,
		&i.ClaimID,
		&i.StatementType,
		&i.Title,
		&i.Content,
		&i.SourceUrl,
		&i.ContactInfo,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClaimProposition,
		&i.ClaimGrade,
		&i.ClaimStatus,
		&i.EntityName,
		&i.EntitySlug,
	)
	return i, err
}

const getDefenseStatementForModeration = `-- name: GetDefenseStatementForModeration :one
SELECT id, claim_id, statement_type, title, content, source_url, contact_info, status, created_at, updated_at
FROM defense_statements
WHERE id = ?
`

func (q *Queries) GetDefenseStatementForModeration(ctx context.Context, id string) (DefenseStatement, error) {
	row := q.db.QueryRowContext(ctx, getDefenseStatementForModeration, id)
	var i DefenseStatement
	err := row.Scan(
		&i.ID,
		&i.ClaimID,
		&i.StatementType,
		&i.Title,
		&i.Content,
		&i.SourceUrl,
		&i.ContactInfo,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublicClaimForManifestation = `-- name: GetPublicClaimForManifestation :one
SELECT
    pcv.claim_id,
    pcv.proposition,
    e.name AS entity_name,
    e.slug AS entity_slug
FROM public_claims_view pcv
JOIN entities e ON e.id = pcv.entity_id
WHERE pcv.claim_id = ?
LIMIT 1
`

type GetPublicClaimForManifestationRow struct {
	ClaimID     string `json:"claim_id"`
	Proposition string `json:"proposition"`
	EntityName  string `json:"entity_name"`
	EntitySlug  string `json:"entity_slug"`
}

func (q *Queries) GetPublicClaimForManifestation(ctx context.Context, claimID string) (GetPublicClaimForManifestationRow, error) {
	row := q.db.QueryRowContext(ctx, getPublicClaimForManifestation, claimID)
	var i GetPublicClaimForManifestationRow
	err := row.Scan(
		&i.ClaimID,
		&i.Proposition,
		&i.EntityName,
		&i.EntitySlug,
	)
	return i, err
}

const insertDefenseStatement = `-- name: InsertDefenseStatement :exec
INSERT INTO defense_statements (
    id, claim_id, statement_type, title, content, source_url, contact_info, status, created_at, updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type InsertDefenseStatementParams struct {
	ID            string `json:"id"`
	ClaimID       string `json:"claim_id"`
	StatementType string `json:"statement_type"`
	Title         string `json:"title"`
	Content       string `json:"content"`
	SourceUrl     string `json:"source_url"`
	ContactInfo   string `json:"contact_info"`
	Status        string `json:"status"`
	CreatedAt     string `json:"created_at"`
	UpdatedAt     string `json:"updated_at"`
}

func (q *Queries) InsertDefenseStatement(ctx context.Context, arg InsertDefenseStatementParams) error {
	_, err := q.db.ExecContext(ctx, insertDefenseStatement,
		arg.ID,
		arg.ClaimID,
		arg.StatementType,
		arg.Title,
		arg.Content,
		arg.SourceUrl,
		arg.ContactInfo,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertDefenseStatementDecision = `-- name: InsertDefenseStatementDecision :exec
INSERT INTO defense_statement_decisions (
    id, statement_id, action, reason, actor, created_at
) VALUES (
    ?, ?, ?, ?, ?, ?
)
`

type InsertDefenseStatementDecisionParams struct {
	ID          string `json:"id"`
	StatementID string `json:"statement_id"`
	Action      string `json:"action"`
	Reason      string `json:"reason"`
	Actor       string `json:"actor"`
	CreatedAt   string `json:"created_at"`
}

func (q *Queries) InsertDefenseStatementDecision(ctx context.Context, arg InsertDefenseStatementDecisionParams) error {
	_, err := q.db.ExecContext(ctx, insertDefenseStatementDecision,
		arg.ID,
		arg.StatementID,
		arg.Action,
		arg.Reason,
		arg.Actor,
		arg.CreatedAt,
	)
	return err
}

const listAdminDefenseStatements = `-- name: ListAdminDefenseStatements :many
SELECT
    ds.id,
    ds.claim_id,
    ds.statement_type,
    ds.title,
    ds.content,
    ds.source_url,
    ds.contact_info,
    ds.status,
    ds.created_at,
    ds.updated_at,
    c.proposition AS claim_proposition,
    c.grade AS claim_grade,
    c.status AS claim_status,
    e.name AS entity_name,
    e.slug AS entity_slug
FROM defense_statements ds
JOIN claims c ON c.id = ds.claim_id
JOIN relationships r ON r.id = c.relationship_id
JOIN entities e ON e.id = r.subject_entity_id
ORDER BY ds.created_at DESC, ds.id DESC
LIMIT ? OFFSET ?
`

type ListAdminDefenseStatementsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListAdminDefenseStatementsRow struct {
	ID               string `json:"id"`
	ClaimID          string `json:"claim_id"`
	StatementType    string `json:"statement_type"`
	Title            string `json:"title"`
	Content          string `json:"content"`
	SourceUrl        string `json:"source_url"`
	ContactInfo      string `json:"contact_info"`
	Status           string `json:"status"`
	CreatedAt        string `json:"created_at"`
	UpdatedAt        string `json:"updated_at"`
	ClaimProposition string `json:"claim_proposition"`
	ClaimGrade       string `json:"claim_grade"`
	ClaimStatus      string `json:"claim_status"`
	EntityName       string `json:"entity_name"`
	EntitySlug       string `json:"entity_slug"`
}

func (q *Queries) ListAdminDefenseStatements(ctx context.Context, arg ListAdminDefenseStatementsParams) ([]ListAdminDefenseStatementsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAdminDefenseStatements, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminDefenseStatementsRow
	for rows.Next() {
		var i ListAdminDefenseStatementsRow
		if err := rows.Scan(
			&i.ID,
			&i.ClaimID,
			&i.StatementType,
			&i.Title,
			&i.Content,
			&i.SourceUrl,
			&i.ContactInfo,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClaimProposition,
			&i.ClaimGrade,
			&i.ClaimStatus,
			&i.EntityName,
			&i.EntitySlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDefenseStatementDecisionsByStatementID = `-- name: ListDefenseStatementDecisionsByStatementID :many
SELECT id, statement_id, action, reason, actor, created_at
FROM defense_statement_decisions
WHERE statement_id = ?
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListDefenseStatementDecisionsByStatementID(ctx context.Context, statementID string) ([]DefenseStatementDecision, error) {
	rows, err := q.db.QueryContext(ctx, listDefenseStatementDecisionsByStatementID, statementID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DefenseStatementDecision
	for rows.Next() {
		var i DefenseStatementDecision
		if err := rows.Scan(
			&i.ID,
			&i.StatementID,
			&i.Action,
			&i.Reason,
			&i.Actor,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicDefenseStatementsByClaimID = `-- name: ListPublicDefenseStatementsByClaimID :many
SELECT
    ds.id,
    ds.claim_id,
    ds.statement_type,
    ds.title,
    ds.content,
    ds.source_url,
    ds.created_at
FROM defense_statements ds
JOIN public_claims_view pcv ON pcv.claim_id = ds.claim_id
WHERE ds.claim_id = ?
  AND ds.status = 'accepted'
ORDER BY ds.created_at ASC, ds.id ASC
`

type ListPublicDefenseStatementsByClaimIDRow struct {
	ID            string `json:"id"`
	ClaimID       string `json:"claim_id"`
	StatementType string `json:"statement_type"`
	Title         string `json:"title"`
	Content       string `json:"content"`
	SourceUrl     string `json:"source_url"`
	CreatedAt     string `json:"created_at"`
}

func (q *Queries) ListPublicDefenseStatementsByClaimID(ctx context.Context, claimID string) ([]ListPublicDefenseStatementsByClaimIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listPublicDefenseStatementsByClaimID, claimID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublicDefenseStatementsByClaimIDRow
	for rows.Next() {
		var i ListPublicDefenseStatementsByClaimIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ClaimID,
			&i.StatementType,
			&i.Title,
			&i.Content,
			&i.SourceUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDefenseStatementStatusWithVersion = `-- name: UpdateDefenseStatementStatusWithVersion :execrows
UPDATE defense_statements
SET status = ?1,
    updated_at = ?2
WHERE id = ?3
  AND updated_at = ?4
`

type UpdateDefenseStatementStatusWithVersionParams struct {
	NewStatus         string `json:"new_status"`
	UpdatedAt         string `json:"updated_at"`
	ID                string `json:"id"`
	ExpectedUpdatedAt string `json:"expected_updated_at"`
}

func (q *Queries) UpdateDefenseStatementStatusWithVersion(ctx context.Context, arg UpdateDefenseStatementStatusWithVersionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateDefenseStatementStatusWithVersion,
		arg.NewStatus,
		arg.UpdatedAt,
		arg.ID,
		arg.ExpectedUpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
