// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: export.sql

package sqlc

import (
	"context"
	"database/sql"
)

const listPublicClaimsForExport = `-- name: ListPublicClaimsForExport :many
SELECT
    pcv.claim_id,
    pcv.relationship_id,
    se.name AS subject_entity_name,
    se.slug AS subject_entity_slug,
    pcv.relationship_type,
    pcv.relationship_summary,
    pcv.context_limits,
    pcv.target_entity_id,
    COALESCE(te.name, '') AS target_entity_name,
    COALESCE(te.slug, '') AS target_entity_slug,
    pcv.case_id,
    COALESCE(cs.name, '') AS case_name,
    COALESCE(cs.slug, '') AS case_slug,
    pcv.proposition,
    pcv.attribution,
    pcv.origin,
    pcv.grade,
    pcv.disposition,
    pcv.metric_eligible,
    pcv.status,
    pcv.context_status,
    pcv.created_at,
    pcv.updated_at
FROM public_claims_view pcv
JOIN entities se ON se.id = pcv.entity_id
LEFT JOIN entities te ON te.id = pcv.target_entity_id
LEFT JOIN cases cs ON cs.id = pcv.case_id
ORDER BY se.name ASC, pcv.grade ASC, pcv.created_at ASC, pcv.claim_id ASC
`

type ListPublicClaimsForExportRow struct {
	ClaimID             string         `json:"claim_id"`
	RelationshipID      string         `json:"relationship_id"`
	SubjectEntityName   string         `json:"subject_entity_name"`
	SubjectEntitySlug   string         `json:"subject_entity_slug"`
	RelationshipType    string         `json:"relationship_type"`
	RelationshipSummary string         `json:"relationship_summary"`
	ContextLimits       string         `json:"context_limits"`
	TargetEntityID      sql.NullString `json:"target_entity_id"`
	TargetEntityName    string         `json:"target_entity_name"`
	TargetEntitySlug    string         `json:"target_entity_slug"`
	CaseID              sql.NullString `json:"case_id"`
	CaseName            string         `json:"case_name"`
	CaseSlug            string         `json:"case_slug"`
	Proposition         string         `json:"proposition"`
	Attribution         string         `json:"attribution"`
	Origin              string         `json:"origin"`
	Grade               string         `json:"grade"`
	Disposition         string         `json:"disposition"`
	MetricEligible      int64          `json:"metric_eligible"`
	Status              string         `json:"status"`
	ContextStatus       string         `json:"context_status"`
	CreatedAt           string         `json:"created_at"`
	UpdatedAt           string         `json:"updated_at"`
}

func (q *Queries) ListPublicClaimsForExport(ctx context.Context) ([]ListPublicClaimsForExportRow, error) {
	rows, err := q.db.QueryContext(ctx, listPublicClaimsForExport)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublicClaimsForExportRow
	for rows.Next() {
		var i ListPublicClaimsForExportRow
		if err := rows.Scan(
			&i.ClaimID,
			&i.RelationshipID,
			&i.SubjectEntityName,
			&i.SubjectEntitySlug,
			&i.RelationshipType,
			&i.RelationshipSummary,
			&i.ContextLimits,
			&i.TargetEntityID,
			&i.TargetEntityName,
			&i.TargetEntitySlug,
			&i.CaseID,
			&i.CaseName,
			&i.CaseSlug,
			&i.Proposition,
			&i.Attribution,
			&i.Origin,
			&i.Grade,
			&i.Disposition,
			&i.MetricEligible,
			&i.Status,
			&i.ContextStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicEntitiesForExport = `-- name: ListPublicEntitiesForExport :many
WITH entity_public_stats AS (
    SELECT
        entity_id,
        COUNT(DISTINCT claim_id) AS public_claims_count,
        CAST(MIN(grade) AS TEXT) AS highest_grade,
        CAST(MAX(updated_at) AS TEXT) AS last_public_updated_at
    FROM public_claims_view
    GROUP BY entity_id
)
SELECT
    e.id,
    e.type,
    e.name,
    e.slug,
    e.category,
    e.role_or_context,
    e.reach,
    e.summary,
    e.relevance,
    e.relevance_rationale,
    stats.public_claims_count,
    stats.highest_grade,
    stats.last_public_updated_at
FROM entities e
JOIN entity_public_stats stats ON stats.entity_id = e.id
ORDER BY e.name ASC, e.id ASC
`

type ListPublicEntitiesForExportRow struct {
	ID                  string `json:"id"`
	Type                string `json:"type"`
	Name                string `json:"name"`
	Slug                string `json:"slug"`
	Category            string `json:"category"`
	RoleOrContext       string `json:"role_or_context"`
	Reach               string `json:"reach"`
	Summary             string `json:"summary"`
	Relevance           int64  `json:"relevance"`
	RelevanceRationale  string `json:"relevance_rationale"`
	PublicClaimsCount   int64  `json:"public_claims_count"`
	HighestGrade        string `json:"highest_grade"`
	LastPublicUpdatedAt string `json:"last_public_updated_at"`
}

func (q *Queries) ListPublicEntitiesForExport(ctx context.Context) ([]ListPublicEntitiesForExportRow, error) {
	rows, err := q.db.QueryContext(ctx, listPublicEntitiesForExport)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublicEntitiesForExportRow
	for rows.Next() {
		var i ListPublicEntitiesForExportRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.Slug,
			&i.Category,
			&i.RoleOrContext,
			&i.Reach,
			&i.Summary,
			&i.Relevance,
			&i.RelevanceRationale,
			&i.PublicClaimsCount,
			&i.HighestGrade,
			&i.LastPublicUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicEvidenceSourcesForExport = `-- name: ListPublicEvidenceSourcesForExport :many
SELECT
    ev.id AS evidence_id,
    ev.claim_id,
    se.name AS subject_entity_name,
    se.slug AS subject_entity_slug,
    ev.summary AS evidence_summary,
    ev.evidence_type,
    es.id AS evidence_source_id,
    es.excerpt,
    es.locator,
    es.role,
    es.status AS evidence_source_status,
    s.id AS source_id,
    s.title AS source_title,
    s.publisher_or_author AS source_publisher,
    s.original_url,
    s.canonical_url,
    s.published_at,
    s.accessed_at,
    s.source_type,
    s.source_access_status
FROM public_claims_view pcv
JOIN entities se ON se.id = pcv.entity_id
JOIN evidence ev ON ev.claim_id = pcv.claim_id
JOIN evidence_sources es ON es.evidence_id = ev.id
JOIN sources s ON s.id = es.source_id
WHERE es.status = 'active'
ORDER BY se.name ASC, pcv.claim_id ASC,
    CASE es.role
        WHEN 'supports' THEN 1
        WHEN 'contradicts' THEN 2
        WHEN 'contextualizes' THEN 3
        ELSE 4
    END ASC,
    es.created_at ASC,
    es.id ASC
`

type ListPublicEvidenceSourcesForExportRow struct {
	EvidenceID           string         `json:"evidence_id"`
	ClaimID              string         `json:"claim_id"`
	SubjectEntityName    string         `json:"subject_entity_name"`
	SubjectEntitySlug    string         `json:"subject_entity_slug"`
	EvidenceSummary      string         `json:"evidence_summary"`
	EvidenceType         string         `json:"evidence_type"`
	EvidenceSourceID     string         `json:"evidence_source_id"`
	Excerpt              string         `json:"excerpt"`
	Locator              string         `json:"locator"`
	Role                 string         `json:"role"`
	EvidenceSourceStatus string         `json:"evidence_source_status"`
	SourceID             string         `json:"source_id"`
	SourceTitle          string         `json:"source_title"`
	SourcePublisher      string         `json:"source_publisher"`
	OriginalUrl          string         `json:"original_url"`
	CanonicalUrl         string         `json:"canonical_url"`
	PublishedAt          sql.NullString `json:"published_at"`
	AccessedAt           sql.NullString `json:"accessed_at"`
	SourceType           string         `json:"source_type"`
	SourceAccessStatus   string         `json:"source_access_status"`
}

func (q *Queries) ListPublicEvidenceSourcesForExport(ctx context.Context) ([]ListPublicEvidenceSourcesForExportRow, error) {
	rows, err := q.db.QueryContext(ctx, listPublicEvidenceSourcesForExport)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublicEvidenceSourcesForExportRow
	for rows.Next() {
		var i ListPublicEvidenceSourcesForExportRow
		if err := rows.Scan(
			&i.EvidenceID,
			&i.ClaimID,
			&i.SubjectEntityName,
			&i.SubjectEntitySlug,
			&i.EvidenceSummary,
			&i.EvidenceType,
			&i.EvidenceSourceID,
			&i.Excerpt,
			&i.Locator,
			&i.Role,
			&i.EvidenceSourceStatus,
			&i.SourceID,
			&i.SourceTitle,
			&i.SourcePublisher,
			&i.OriginalUrl,
			&i.CanonicalUrl,
			&i.PublishedAt,
			&i.AccessedAt,
			&i.SourceType,
			&i.SourceAccessStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
