// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
)

type Case struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Slug        string `json:"slug"`
	Description string `json:"description"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

type Claim struct {
	ID                string         `json:"id"`
	RelationshipID    string         `json:"relationship_id"`
	Proposition       string         `json:"proposition"`
	Attribution       string         `json:"attribution"`
	Origin            string         `json:"origin"`
	Grade             string         `json:"grade"`
	Disposition       string         `json:"disposition"`
	MetricEligible    int64          `json:"metric_eligible"`
	Status            string         `json:"status"`
	ImportRunID       sql.NullString `json:"import_run_id"`
	CreatedAt         string         `json:"created_at"`
	UpdatedAt         string         `json:"updated_at"`
	ContextStatus     string         `json:"context_status"`
	QuarantineReasons string         `json:"quarantine_reasons"`
}

type Entity struct {
	ID                 string `json:"id"`
	Type               string `json:"type"`
	Name               string `json:"name"`
	NormalizedName     string `json:"normalized_name"`
	Slug               string `json:"slug"`
	RoleOrContext      string `json:"role_or_context"`
	Summary            string `json:"summary"`
	Relevance          int64  `json:"relevance"`
	RelevanceRationale string `json:"relevance_rationale"`
	CreatedAt          string `json:"created_at"`
	UpdatedAt          string `json:"updated_at"`
	Category           string `json:"category"`
	Reach              string `json:"reach"`
}

type EntityAlias struct {
	ID              string `json:"id"`
	EntityID        string `json:"entity_id"`
	Alias           string `json:"alias"`
	NormalizedAlias string `json:"normalized_alias"`
	CreatedAt       string `json:"created_at"`
}

type Evidence struct {
	ID           string `json:"id"`
	ClaimID      string `json:"claim_id"`
	Summary      string `json:"summary"`
	EvidenceType string `json:"evidence_type"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

type EvidenceSource struct {
	ID         string `json:"id"`
	EvidenceID string `json:"evidence_id"`
	SourceID   string `json:"source_id"`
	Excerpt    string `json:"excerpt"`
	Locator    string `json:"locator"`
	Role       string `json:"role"`
	Status     string `json:"status"`
	CreatedAt  string `json:"created_at"`
	UpdatedAt  string `json:"updated_at"`
}

type ImportRun struct {
	ID             string         `json:"id"`
	FilePath       string         `json:"file_path"`
	FileHash       string         `json:"file_hash"`
	Origin         string         `json:"origin"`
	MappingVersion string         `json:"mapping_version"`
	Status         string         `json:"status"`
	IsDryRun       int64          `json:"is_dry_run"`
	SummaryCounts  string         `json:"summary_counts"`
	SummaryReport  string         `json:"summary_report"`
	ErrorMessage   sql.NullString `json:"error_message"`
	CreatedAt      string         `json:"created_at"`
	CompletedAt    sql.NullString `json:"completed_at"`
}

type MonitoringCandidate struct {
	ID                         string         `json:"id"`
	MonitoringRunID            string         `json:"monitoring_run_id"`
	Fingerprint                string         `json:"fingerprint"`
	FingerprintVersion         int64          `json:"fingerprint_version"`
	EntityName                 string         `json:"entity_name"`
	NormalizedEntityName       string         `json:"normalized_entity_name"`
	TargetEntityName           string         `json:"target_entity_name"`
	NormalizedTargetEntityName string         `json:"normalized_target_entity_name"`
	CaseName                   string         `json:"case_name"`
	NormalizedCaseName         string         `json:"normalized_case_name"`
	RelationshipType           string         `json:"relationship_type"`
	Proposition                string         `json:"proposition"`
	SuggestedGrade             string         `json:"suggested_grade"`
	SourceUrl                  string         `json:"source_url"`
	CanonicalUrl               string         `json:"canonical_url"`
	SourceTitle                string         `json:"source_title"`
	PublisherOrAuthor          string         `json:"publisher_or_author"`
	PublishedAt                sql.NullString `json:"published_at"`
	Excerpt                    string         `json:"excerpt"`
	Locator                    string         `json:"locator"`
	ContextLimits              string         `json:"context_limits"`
	TechnicalConfidence        float64        `json:"technical_confidence"`
	RawPayload                 string         `json:"raw_payload"`
	EditorialStatus            string         `json:"editorial_status"`
	IsDuplicate                int64          `json:"is_duplicate"`
	DuplicateReason            string         `json:"duplicate_reason"`
	CanonicalCandidateID       sql.NullString `json:"canonical_candidate_id"`
	ResolvedSubjectEntityID    sql.NullString `json:"resolved_subject_entity_id"`
	ResolvedTargetEntityID     sql.NullString `json:"resolved_target_entity_id"`
	ResolvedCaseID             sql.NullString `json:"resolved_case_id"`
	PublishedClaimID           sql.NullString `json:"published_claim_id"`
	StructuralGatePassed       sql.NullInt64  `json:"structural_gate_passed"`
	StructuralGateReasons      string         `json:"structural_gate_reasons"`
	SemanticGatePassed         sql.NullInt64  `json:"semantic_gate_passed"`
	SemanticGateReasons        string         `json:"semantic_gate_reasons"`
	PolicyAction               string         `json:"policy_action"`
	PolicyReasons              string         `json:"policy_reasons"`
	CreatedAt                  string         `json:"created_at"`
	UpdatedAt                  string         `json:"updated_at"`
}

type MonitoringRun struct {
	ID                   string          `json:"id"`
	Status               string          `json:"status"`
	Query                string          `json:"query"`
	DiscoveryProvider    string          `json:"discovery_provider"`
	DiscoveryModel       string          `json:"discovery_model"`
	VerificationProvider string          `json:"verification_provider"`
	VerificationModel    string          `json:"verification_model"`
	PromptTokens         int64           `json:"prompt_tokens"`
	CompletionTokens     int64           `json:"completion_tokens"`
	TotalTokens          int64           `json:"total_tokens"`
	EstimatedCost        sql.NullFloat64 `json:"estimated_cost"`
	WebSearchCalls       int64           `json:"web_search_calls"`
	ErrorMessage         sql.NullString  `json:"error_message"`
	SummaryCounts        string          `json:"summary_counts"`
	TechnicalSummary     string          `json:"technical_summary"`
	CreatedAt            string          `json:"created_at"`
	CompletedAt          sql.NullString  `json:"completed_at"`
}

type PublicClaimsView struct {
	ClaimID             string         `json:"claim_id"`
	RelationshipID      string         `json:"relationship_id"`
	EntityID            string         `json:"entity_id"`
	TargetEntityID      sql.NullString `json:"target_entity_id"`
	CaseID              sql.NullString `json:"case_id"`
	RelationshipType    string         `json:"relationship_type"`
	RelationshipSummary string         `json:"relationship_summary"`
	ContextLimits       string         `json:"context_limits"`
	Proposition         string         `json:"proposition"`
	Attribution         string         `json:"attribution"`
	Origin              string         `json:"origin"`
	Grade               string         `json:"grade"`
	Disposition         string         `json:"disposition"`
	MetricEligible      int64          `json:"metric_eligible"`
	Status              string         `json:"status"`
	ContextStatus       string         `json:"context_status"`
	CreatedAt           string         `json:"created_at"`
	UpdatedAt           string         `json:"updated_at"`
}

type Relationship struct {
	ID               string         `json:"id"`
	SubjectEntityID  string         `json:"subject_entity_id"`
	TargetEntityID   sql.NullString `json:"target_entity_id"`
	CaseID           sql.NullString `json:"case_id"`
	RelationshipType string         `json:"relationship_type"`
	Summary          string         `json:"summary"`
	ContextLimits    string         `json:"context_limits"`
	CreatedAt        string         `json:"created_at"`
	UpdatedAt        string         `json:"updated_at"`
}

type SemanticEvaluation struct {
	ID                       string `json:"id"`
	MonitoringCandidateID    string `json:"monitoring_candidate_id"`
	Provider                 string `json:"provider"`
	Model                    string `json:"model"`
	SchemaVersion            string `json:"schema_version"`
	IdentityMatch            int64  `json:"identity_match"`
	ClaimSupported           int64  `json:"claim_supported"`
	ClaimOverstatesSource    int64  `json:"claim_overstates_source"`
	AttributionExplicit      int64  `json:"attribution_explicit"`
	GradeCompatible          int64  `json:"grade_compatible"`
	ContainsIllicitInference int64  `json:"contains_illicit_inference"`
	Uncertainties            string `json:"uncertainties"`
	RecommendedAction        string `json:"recommended_action"`
	RawResponse              string `json:"raw_response"`
	CreatedAt                string `json:"created_at"`
}

type Source struct {
	ID                    string         `json:"id"`
	Title                 string         `json:"title"`
	PublisherOrAuthor     string         `json:"publisher_or_author"`
	OriginalUrl           string         `json:"original_url"`
	CanonicalUrl          string         `json:"canonical_url"`
	PublishedAt           sql.NullString `json:"published_at"`
	AccessedAt            sql.NullString `json:"accessed_at"`
	SourceType            string         `json:"source_type"`
	SourceAccessStatus    string         `json:"source_access_status"`
	SourceAccessCheckedAt sql.NullString `json:"source_access_checked_at"`
	HttpStatus            sql.NullInt64  `json:"http_status"`
	NormalizedErrorCode   sql.NullString `json:"normalized_error_code"`
	CreatedAt             string         `json:"created_at"`
	UpdatedAt             string         `json:"updated_at"`
}
