// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
)

type Case struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Slug        string `json:"slug"`
	Description string `json:"description"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

type Claim struct {
	ID                string         `json:"id"`
	RelationshipID    string         `json:"relationship_id"`
	Proposition       string         `json:"proposition"`
	Attribution       string         `json:"attribution"`
	Origin            string         `json:"origin"`
	Grade             string         `json:"grade"`
	Disposition       string         `json:"disposition"`
	MetricEligible    int64          `json:"metric_eligible"`
	Status            string         `json:"status"`
	ImportRunID       sql.NullString `json:"import_run_id"`
	CreatedAt         string         `json:"created_at"`
	UpdatedAt         string         `json:"updated_at"`
	ContextStatus     string         `json:"context_status"`
	QuarantineReasons string         `json:"quarantine_reasons"`
}

type Entity struct {
	ID                 string `json:"id"`
	Type               string `json:"type"`
	Name               string `json:"name"`
	NormalizedName     string `json:"normalized_name"`
	Slug               string `json:"slug"`
	RoleOrContext      string `json:"role_or_context"`
	Summary            string `json:"summary"`
	Relevance          int64  `json:"relevance"`
	RelevanceRationale string `json:"relevance_rationale"`
	CreatedAt          string `json:"created_at"`
	UpdatedAt          string `json:"updated_at"`
	Category           string `json:"category"`
	Reach              string `json:"reach"`
}

type EntityAlias struct {
	ID              string `json:"id"`
	EntityID        string `json:"entity_id"`
	Alias           string `json:"alias"`
	NormalizedAlias string `json:"normalized_alias"`
	CreatedAt       string `json:"created_at"`
}

type Evidence struct {
	ID           string `json:"id"`
	ClaimID      string `json:"claim_id"`
	Summary      string `json:"summary"`
	EvidenceType string `json:"evidence_type"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

type EvidenceSource struct {
	ID         string `json:"id"`
	EvidenceID string `json:"evidence_id"`
	SourceID   string `json:"source_id"`
	Excerpt    string `json:"excerpt"`
	Locator    string `json:"locator"`
	Role       string `json:"role"`
	Status     string `json:"status"`
	CreatedAt  string `json:"created_at"`
	UpdatedAt  string `json:"updated_at"`
}

type ImportRun struct {
	ID             string         `json:"id"`
	FilePath       string         `json:"file_path"`
	FileHash       string         `json:"file_hash"`
	Origin         string         `json:"origin"`
	MappingVersion string         `json:"mapping_version"`
	Status         string         `json:"status"`
	IsDryRun       int64          `json:"is_dry_run"`
	SummaryCounts  string         `json:"summary_counts"`
	SummaryReport  string         `json:"summary_report"`
	ErrorMessage   sql.NullString `json:"error_message"`
	CreatedAt      string         `json:"created_at"`
	CompletedAt    sql.NullString `json:"completed_at"`
}

type Relationship struct {
	ID               string         `json:"id"`
	SubjectEntityID  string         `json:"subject_entity_id"`
	TargetEntityID   sql.NullString `json:"target_entity_id"`
	CaseID           sql.NullString `json:"case_id"`
	RelationshipType string         `json:"relationship_type"`
	Summary          string         `json:"summary"`
	ContextLimits    string         `json:"context_limits"`
	CreatedAt        string         `json:"created_at"`
	UpdatedAt        string         `json:"updated_at"`
}

type Source struct {
	ID                    string         `json:"id"`
	Title                 string         `json:"title"`
	PublisherOrAuthor     string         `json:"publisher_or_author"`
	OriginalUrl           string         `json:"original_url"`
	CanonicalUrl          string         `json:"canonical_url"`
	PublishedAt           sql.NullString `json:"published_at"`
	AccessedAt            sql.NullString `json:"accessed_at"`
	SourceType            string         `json:"source_type"`
	SourceAccessStatus    string         `json:"source_access_status"`
	SourceAccessCheckedAt sql.NullString `json:"source_access_checked_at"`
	HttpStatus            sql.NullInt64  `json:"http_status"`
	NormalizedErrorCode   sql.NullString `json:"normalized_error_code"`
	CreatedAt             string         `json:"created_at"`
	UpdatedAt             string         `json:"updated_at"`
}
